name: notify pr approve

on:
  pull_request:
    types: [submitted]

jobs:
  Notify:
    runs-on: [ubuntu-latest]
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_BOT_CHANNEL }}
          payload: |
            {
                "text": "",
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "PR μΉμΈν–μµλ‹λ‹¤π‘\n<${{ github.event.comment.html_url }}|PR ν™•μΈν•λ¬ κ°€κΈ°>"
                        }
                    }
                ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
