name: notify pr review

on:
  pull_request:
    types: [review_requested]

jobs:
  Notify:
    runs-on: [ubuntu-latest]
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ secrets.SLACK_BOT_CHANNEL }}
          payload: |
            {
              "text": "SLACK PR μ•λ¦Ό",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "PR ν–μµλ‹λ‹¤π‘\n<${{ github.event.comment.html_url }}|PR ν™•μΈν•λ¬ κ°€κΈ°>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
