name: notify pr review

on:
  pull_request:
    types: [opened, reopened]

jobs:
  Notify:
    runs-on: [ubuntu-latest]
    steps:
      - name: Send Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "SLACK PR μ•λ¦Ό",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "PR λ“±λ΅ν–μµλ‹λ‹¤π‘\n<${{ github.event.pull_request.html_url }}|PR ν™•μΈν•λ¬ κ°€κΈ°>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PR_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
